# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "puppetlabs/ubuntu-14.04-64-puppet"

  config.vm.provision "puppet" do |puppet|
    puppet.environment = 'test'
    puppet.environment_path = 'environments'
    puppet.working_directory = '/tmp/vagrant-puppet/environments/test'
  end

end
